package com.yandex.keycloak.ydb.realm

import com.yandex.keycloak.ydb.common.AttributePrefixes.INTERNAL_ATTRIBUTE_PREFIX

object YdbRealmAttributeConstants {
  const val DISPLAY_NAME: String = INTERNAL_ATTRIBUTE_PREFIX + "displayName"
  const val DISPLAY_NAME_HTML: String = INTERNAL_ATTRIBUTE_PREFIX + "displayNameHtml"
  const val IS_ENABLED: String = INTERNAL_ATTRIBUTE_PREFIX + "enabled"

  const val SSL_REQUIRED: String = INTERNAL_ATTRIBUTE_PREFIX + "sslRequired"
  const val IS_REGISTRATION_ALLOWED: String = INTERNAL_ATTRIBUTE_PREFIX + "isRegistrationAllowed"
  const val IS_REGISTRATION_EMAIL_AS_USERNAME: String = INTERNAL_ATTRIBUTE_PREFIX + "isRegistrationEmailAsUsername"
  const val IS_REMEMBER_ME: String = INTERNAL_ATTRIBUTE_PREFIX + "isRememberMe"
  const val IS_EDIT_USERNAME_ALLOWED: String = INTERNAL_ATTRIBUTE_PREFIX + "isEditUsernameAllowed"
  const val IS_USER_MANAGED_ACCESS_ALLOWED: String = INTERNAL_ATTRIBUTE_PREFIX + "isUserManagedAccessAllowed"
  const val IS_ORGANIZATIONS_ENABLED: String = INTERNAL_ATTRIBUTE_PREFIX + "organizationsEnabled"
  const val IS_ADMIN_PERMISSIONS_ENABLED: String = INTERNAL_ATTRIBUTE_PREFIX + "adminPermissionsEnabled"
  const val IS_VERIFIABLE_CREDENTIALS_ENABLED: String = INTERNAL_ATTRIBUTE_PREFIX + "verifiableCredentialsEnabled"
  const val IS_BRUTE_FORCE_PROTECTED: String = INTERNAL_ATTRIBUTE_PREFIX + "isBruteForceProtected"
  const val IS_PERMANENT_LOCKOUT: String = INTERNAL_ATTRIBUTE_PREFIX + "isPermanentLockout"
  const val MAX_TEMPORARY_LOCKOUTS: String = INTERNAL_ATTRIBUTE_PREFIX + "maxTemporaryLockouts"
  const val BRUTE_FORCE_STRATEGY: String = INTERNAL_ATTRIBUTE_PREFIX + "bruteForceStrategy"
  const val MAX_FAILURE_WAIT_SECONDS: String = INTERNAL_ATTRIBUTE_PREFIX + "maxFailureWaitSeconds"
  const val WAIT_INCREMENT_SECONDS: String = INTERNAL_ATTRIBUTE_PREFIX + "waitIncrementSeconds"
  const val MINIMUM_QUICK_LOGIN_WAIT_SECONDS: String = INTERNAL_ATTRIBUTE_PREFIX + "minimumQuickLoginWaitSeconds"
  const val QUICK_LOGIN_CHECK_MILLI_SECONDS: String = INTERNAL_ATTRIBUTE_PREFIX + "quickLoginCheckMilliSeconds"
  const val MAX_DELTA_TIME_SECONDS: String = INTERNAL_ATTRIBUTE_PREFIX + "maxDeltaTimeSeconds"
  const val FAILURE_FACTOR: String = INTERNAL_ATTRIBUTE_PREFIX + "failureFactor"
  const val VERIFY_EMAIL: String = INTERNAL_ATTRIBUTE_PREFIX + "verifyEmail"
  const val LOGIN_WITH_EMAIL_ALLOWED: String = INTERNAL_ATTRIBUTE_PREFIX + "loginWithEmailAllowed"
  const val IS_DUPLICATE_EMAILS_ALLOWED: String = INTERNAL_ATTRIBUTE_PREFIX + "isDuplicateEmailsAllowed"
  const val IS_RESET_PASSWORD_ALLOWED: String = INTERNAL_ATTRIBUTE_PREFIX + "isResetPasswordAllowed"
  const val DEFAULT_SIG_ALGORITHM: String = INTERNAL_ATTRIBUTE_PREFIX + "defaultSigAlgorithm"
  const val IS_REVOKE_REFRESH_TOKEN: String = INTERNAL_ATTRIBUTE_PREFIX + "isRevokeRefreshToken"
  const val REFRESH_TOKEN_MAX_REUSE: String = INTERNAL_ATTRIBUTE_PREFIX + "refreshTokenMaxReuse"
  const val SSO_SESSION_IDLE_TIMEOUT: String = INTERNAL_ATTRIBUTE_PREFIX + "ssoSessionIdleTimeout"
  const val SSO_SESSION_MAX_LIFESPAN: String = INTERNAL_ATTRIBUTE_PREFIX + "ssoSessionMaxLifespan"
  const val SSO_SESSION_IDLE_TIMEOUT_REMEMBER_ME: String = INTERNAL_ATTRIBUTE_PREFIX + "ssoSessionIdleTimeoutRememberMe"
  const val SSO_SESSION_MAX_LIFESPAN_REMEMBER_ME: String = INTERNAL_ATTRIBUTE_PREFIX + "ssoSessionMaxLifespanRememberMe"
  const val OFFLINE_SESSION_IDLE_TIMEOUT: String = INTERNAL_ATTRIBUTE_PREFIX + "offlineSessionIdleTimeout"
  const val ACCESS_TOKEN_LIFESPAN: String = INTERNAL_ATTRIBUTE_PREFIX + "accessTokenLifespan"
  const val IS_OFFLINE_SESSION_MAX_LIFESPAN_ENABLED: String =
    INTERNAL_ATTRIBUTE_PREFIX + "isOfflineSessionMaxLifespanEnabled"
  const val OFFLINE_SESSION_MAX_LIFESPAN: String = INTERNAL_ATTRIBUTE_PREFIX + "offlineSessionMaxLifespan"
  const val CLIENT_SESSION_IDLE_TIMEOUT: String = INTERNAL_ATTRIBUTE_PREFIX + "clientSessionIdleTimeout"
  const val CLIENT_SESSION_MAX_LIFESPAN: String = INTERNAL_ATTRIBUTE_PREFIX + "clientSessionMaxLifespan"
  const val CLIENT_OFFLINE_SESSION_IDLE_TIMEOUT: String = INTERNAL_ATTRIBUTE_PREFIX + "clientOfflineSessionIdleTimeout"
  const val CLIENT_OFFLINE_SESSION_MAX_LIFESPAN: String = INTERNAL_ATTRIBUTE_PREFIX + "clientOfflineSessionMaxLifespan"
  const val ACCESS_TOKEN_LIFESPAN_FOR_IMPLICIT_FLOW: String =
    INTERNAL_ATTRIBUTE_PREFIX + "accessTokenLifespanForImplicitFlow"
  const val ACCESS_CODE_LIFESPAN: String = INTERNAL_ATTRIBUTE_PREFIX + "accessCodeLifespan"
  const val ACCESS_CODE_LIFESPAN_USER_ACTION: String = INTERNAL_ATTRIBUTE_PREFIX + "accessCodeLifespanUserAction"
  const val ACCESS_CODE_LIFESPAN_LOGIN: String = INTERNAL_ATTRIBUTE_PREFIX + "accessCodeLifespanLogin"
  const val ACTION_TOKEN_GENERATED_BY_ADMIN_LIFESPAN: String =
    INTERNAL_ATTRIBUTE_PREFIX + "actionTokenGeneratedByAdminLifespan"
  const val ACTION_TOKEN_GENERATED_BY_USER_LIFESPAN: String =
    INTERNAL_ATTRIBUTE_PREFIX + "actionTokenGeneratedByUserLifespan"
  const val PASSWORD_POLICY: String = INTERNAL_ATTRIBUTE_PREFIX + "passwordPolicy"
  const val REQUIRED_CREDENTIALS: String = INTERNAL_ATTRIBUTE_PREFIX + "requiredCredentials"
  const val OTP_POLICY: String = INTERNAL_ATTRIBUTE_PREFIX + "otpPolicy"
  const val WEB_AUTHN_POLICY: String = INTERNAL_ATTRIBUTE_PREFIX + "webAuthnPolicy"
  const val WEB_AUTHN_POLICY_PASSWORDLESS: String = INTERNAL_ATTRIBUTE_PREFIX + "webAuthnPolicyPasswordless"
  const val BROWSER_SECURITY_HEADERS: String = INTERNAL_ATTRIBUTE_PREFIX + "browserSecurityHeaders"
  const val SMTP_CONFIG: String = INTERNAL_ATTRIBUTE_PREFIX + "smtpConfig"
  const val BROWSER_FLOW: String = INTERNAL_ATTRIBUTE_PREFIX + "browserFlow"
  const val REGISTRATION_FLOW: String = INTERNAL_ATTRIBUTE_PREFIX + "registrationFlow"
  const val DIRECT_GRANT_FLOW: String = INTERNAL_ATTRIBUTE_PREFIX + "directGrantFlow"
  const val RESET_CREDENTIALS_FLOW: String = INTERNAL_ATTRIBUTE_PREFIX + "resetCredentialsFlow"
  const val CLIENT_AUTHENTICATION_FLOW: String = INTERNAL_ATTRIBUTE_PREFIX + "clientAuthenticationFlow"
  const val DOCKER_AUTHENTICATION_FLOW: String = INTERNAL_ATTRIBUTE_PREFIX + "dockerAuthenticationFlow"
  const val FIRST_BROKER_LOGIN_FLOW: String = INTERNAL_ATTRIBUTE_PREFIX + "firstBrokerLoginFlow"
  const val AUTHENTICATION_FLOWS: String = INTERNAL_ATTRIBUTE_PREFIX + "authenticationFlows"
  const val AUTHENTICATION_EXECUTION_MODELS: String = INTERNAL_ATTRIBUTE_PREFIX + "authenticationExecutionModels"
  const val AUTHENTICATOR_CONFIG_MODELS: String = INTERNAL_ATTRIBUTE_PREFIX + "authenticatorConfigModels"
  const val REQUIRED_ACTION_CONFIG_MODELS: String = INTERNAL_ATTRIBUTE_PREFIX + "requiredActionConfigModels"
  const val REQUIRED_ACTION_PROVIDER_MODELS: String = INTERNAL_ATTRIBUTE_PREFIX + "requiredActionProviderModels"
  const val IDENTITY_PROVIDERS: String = INTERNAL_ATTRIBUTE_PREFIX + "identityProviders"
  const val IDENTITY_PROVIDER_MAPPERS: String = INTERNAL_ATTRIBUTE_PREFIX + "identityProviderMappers"
  const val COMPONENTS: String = INTERNAL_ATTRIBUTE_PREFIX + "components"
  const val LOGIN_THEME: String = INTERNAL_ATTRIBUTE_PREFIX + "loginTheme"
  const val ACCOUNT_THEME: String = INTERNAL_ATTRIBUTE_PREFIX + "accountTheme"
  const val ADMIN_THEME: String = INTERNAL_ATTRIBUTE_PREFIX + "adminTheme"
  const val EMAIL_THEME: String = INTERNAL_ATTRIBUTE_PREFIX + "emailTheme"
  const val NOT_BEFORE: String = INTERNAL_ATTRIBUTE_PREFIX + "notBefore"
  const val IS_EVENTS_ENABLED: String = INTERNAL_ATTRIBUTE_PREFIX + "isEventsEnabled"
  const val EVENTS_EXPIRATION: String = INTERNAL_ATTRIBUTE_PREFIX + "eventsExpiration"
  const val EVENT_LISTENERS: String = INTERNAL_ATTRIBUTE_PREFIX + "eventListeners"
  const val ENABLED_EVENT_TYPES: String = INTERNAL_ATTRIBUTE_PREFIX + "enabledEventTypes"
  const val IS_ADMIN_EVENTS_ENABLED: String = INTERNAL_ATTRIBUTE_PREFIX + "isAdminEventsEnabled"
  const val IS_ADMIN_EVENTS_DETAILS_ENABLED: String = INTERNAL_ATTRIBUTE_PREFIX + "isAdminEventsDetailsEnabled"
  const val MASTER_ADMIN_CLIENT_ID: String = INTERNAL_ATTRIBUTE_PREFIX + "masterAdminClientId"
  const val IS_INTERNATIONALIZATION_ENABLED: String = INTERNAL_ATTRIBUTE_PREFIX + "isInternationalizationEnabled"
  const val SUPPORTED_LOCALES: String = INTERNAL_ATTRIBUTE_PREFIX + "supportedLocales"
  const val DEFAULT_LOCALE: String = INTERNAL_ATTRIBUTE_PREFIX + "defaultLocale"
  const val LOCALIZATION_TEXTS: String = INTERNAL_ATTRIBUTE_PREFIX + "localizationTexts"
  const val DEFAULT_GROUP_IDS: String = INTERNAL_ATTRIBUTE_PREFIX + "defaultGroupIds"
  const val DEFAULT_ROLE_ID: String = INTERNAL_ATTRIBUTE_PREFIX + "defaultRoleId"
  const val DEFAULT_CLIENT_SCOPE_ID: String = INTERNAL_ATTRIBUTE_PREFIX + "defaultClientScopeId"
  const val OPTIONAL_CLIENT_SCOPE_ID: String = INTERNAL_ATTRIBUTE_PREFIX + "optionalClientScopeId"
}