CREATE TABLE IF NOT EXISTS `DEFAULT_CLIENT_SCOPE`
(
    `REALM_ID`      Utf8 NOT NULL,
    `SCOPE_ID`      Utf8 NOT NULL,
    `DEFAULT_SCOPE` Bool NOT NULL DEFAULT false,

    PRIMARY KEY (`REALM_ID`, `SCOPE_ID`)
);
